### ISSUE TITLE
Error when register

### ISSUE THREAD

**Issue by ManuCart** [bahamas10/hue-cli#13]
````
hue register
please go and press the link button on your base station
failed to pair to Hue Base Station 192.168.0.12

/usr/local/lib/node_modules/hue-cli/hue-cli.js:251
        throw err;
        ^
Error
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/helpers.js:7:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/Hue.js:5:20)
    at Module._compile (module.js:541:32)
````

**Comment by Baloobear** [comment]
+1

I have the same problem. It's impossible to register the hue-cli at the hue bridge. I have the current round-edged box-shaped bridge (and registering other apps worked fine, so far).

I use node v4.4.7 (LTS).

**Comment by pieshop** [comment]
+1

Just upgraded to the second version of the bridge (homekit)

$hue search : finds the bridge ok.
$hue config : "code": "ETIMEDOUT"
$hue --host xxx.xxx.xxx.xxx register : returns

please go and press the link button on your base station
failed to pair to Hue Base Station xxx.xxx.xxx.xxx

/Users/stephenhamilton/.npm-global/lib/node_modules/hue-cli/hue-cli.js:251
        throw err;
        ^
Error
    at Object.<anonymous> (/Users/stephenhamilton/.npm-global/lib/node_modules/hue-cli/node_modules/hue.js/lib/helpers.js:7:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/stephenhamilton/.npm-global/lib/node_modules/hue-cli/node_modules/hue.js/lib/Hue.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by jaredpalmer** [comment]
+1

**Comment by mave007** [comment]
same problem here.

One thing to notice is that I have replaced the old bridge (round) with the squared new one and 
hue config shows that the bridge have been replaced.

Still not able to register

`/usr/local/lib/node_modules/hue-cli/hue-cli.js:251
        throw err;
        ^
Error
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/helpers.js:7:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/Hue.js:5:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

**Comment by niklasR** [comment]
+1 - with the old bridge.

**Comment by pieshop** [comment]
I actually found I was already registered.

Once I did hue -H xx.xx.xx.xx config I could see the config - it was defaulting to the old ip and so erroring.

So I did hue -host xx.xx.xx.xx --save, which saved the new ip in the config file, and from there 'hue lights' and other commands worked fine.

**Comment by pieshop** [comment]
As a side note - when I switched the bridge the only way I could get the transfer to work was to use a new dhcp assigned ip address!

**Comment by mattbucci** [comment]
fixed by https://github.com/bahamas10/hue-cli/pull/14

**Comment by Baloobear** [comment]
@bahamas10 will u plz merge the pull request(s)?! thanks.

**Comment by bahamas10** [comment]
@Baloobear plz give me more than 8 hours to respond! :p

I only have the old bridge, so I will be limited to testing the new bridge sometime this weekend when I go to my friends house who has it himself.

My comments to the pr by @mattbucci will be that thread

**Comment by TwizzyDizzy** [comment]
Have the new bridge here, so could provide testing if needed.

**Comment by dopeghoti** [comment]
Same problem here on a fresh install with a first-gen bridge:

```
$ hue -H 192.168.x.y register
please go and press the link button on your base station
failed to pair to Hue Base Station 192.168.x.y

/usr/local/lib/node_modules/hue-cli/hue-cli.js:251
        throw err;
        ^
Error
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/helpers.js:7:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/Hue.js:5:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by TwizzyDizzy** [comment]
Please refer to https://github.com/bahamas10/hue-cli/pull/14. This issue has recently been fixed by @mattbucci and awaits merging into master by @bahamas10.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Hey @ManuCart,

please test with the latest version from `npm` and close this issue as it should be fixed by the PR mentioned above.

Cheers
Thomas

**Comment by ManuCart** [comment]
Yes!!!! Working
Thanks you all for help
