### ISSUE TITLE
 TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by Paasmer** [bahamas10/hue-cli#27]
Hi, we are using the Hue-cli library, today while working we found the following issue which was not there earlier.

```
Hue Base Station paired!
username: kEEmOnMDlliWwsi6JSPsO6SLwyfvlWCFaqHsBbVP
config file written to `undefined`
fs.js:638
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.writeFileSync (fs.js:1287:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/hue-cli/hue-cli.js:285:10)
    at Request._callback (/usr/local/lib/node_modules/hue-cli/node_modules/hue.js/lib/Hue.js:188:10)
    at Request.self.callback (/usr/local/lib/node_modules/hue-cli/node_modules/request/main.js:122:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/hue-cli/node_modules/request/main.js:661:16)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
![screenshot 62](https://user-images.githubusercontent.com/25072282/30269652-3248a59e-9707-11e7-85fc-637565bf54de.png)
```
Please Help to resolve this issue

**Comment by bahamas10** [comment]
ah darn, that must be from the changes i made over the weekend - will look at this today thanks!

**Comment by bahamas10** [comment]
```
$ npm publish
+ hue-cli@0.3.1
```
