### ISSUE TITLE
Exception thrown with node 0.12.x

### ISSUE THREAD

**Issue by srubben** [bahamas10/hue-cli#6]
When using node 0.12.x (tested with 0.12.1 and 0.12.3) the following exception is thrown:

```
dgram.js:367
    throw errnoException(err, 'getsockname');
          ^
Error: getsockname EINVAL
    at exports._errnoException (util.js:746:11)
    at Socket.address (dgram.js:367:11)
    at next (/home/sven/.nvm/v0.10.36/lib/node_modules/hue-cli/node_modules/hue.js/lib/Discoverer.js:27:25)
    at Object.module.exports [as discover] (/home/sven/.nvm/v0.10.36/lib/node_modules/hue-cli/node_modules/hue.js/lib/Discoverer.js:21:5)
    at Object.<anonymous> (/home/sven/.nvm/v0.10.36/lib/node_modules/hue-cli/hue-cli.js:257:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

It works correctly with node 0.10.36.

**Comment by bahamas10** [comment]
confirmed... issue lies in discovery in hue.js module... will dig in.

**Comment by bahamas10** [comment]
fix here https://github.com/thatguydan/hue.js/pull/8

**Comment by YBerth13** [comment]
I forked this repo and pointed the hue.js dependency to bahamas10's fix at [thatguydan/hue.js#8](thatguydan/hue.js#8). Not sure if it will get merged into this repo or not, but if you need to get it working you should be able to install hue-cli using my forked version by running `sudo npm install -g https://github.com/YBerth13/hue-cli/tarball/master`

**Comment by TwizzyDizzy** [comment]
cross-referencing with #9 as they are probably related.

Cheers
Thomas

**Comment by bahamas10** [comment]
Is this still an issue?

**Comment by TwizzyDizzy** [comment]
As nodejs 0.10 and 0.12 are end-of-life (see https://github.com/nodejs/LTS#lts-schedule1), this issue can be closed.

Cheers
Thomas
